### ISSUE TITLE
Readme file 

### ISSUE THREAD

**Issue by parth-bril22** [mohsenMahmoodzadeh/Book-Crossing-Recommender-System#1]
Please assign the right path to file Data_Preprocessing.ipynb

**Comment by mohsenMahmoodzadeh** [comment]
Hello dear friend. Thanks for pointing to the data path. Due to file size of datasets, I ignored pushing them to repository. But you can access to the dataset files from the following link:

https://drive.google.com/drive/folders/11MK-LmcVG2yauKRoLg8IVqoqWUIPg1CA?usp=sharing

You can wrap the files in a folder and modify the folder path while reading them in the notebook. Hope it helps!

**Comment by parth-bril22** [comment]
Hello Mohsen,

Hope you are doing well.Thank you for your email.

Thanks & Regards
Parth Patel
